
const data= [
    {"id":"1",
      "Vendor Code":"1015",
      "Title":"Lego",
      "Price":1,
      "Prev Price":350,
      "img":"https://picsum.photos/200"
    },
    {"id":"2",
      "Vendor Code":"1025",
      "Title":"sdgjoig sfldjsfd",
      "Price":2,
      "Prev Price":350,
      "img":"https://picsum.photos/id/1/200"
    },
    {"id":"3",
      "Vendor Code":"1035",
      "Title":"sdgjoig sfldjsfd",
      "Price":3,
      "Prev Price":350,
       "img":"https://picsum.photos/id/2/200"
    },
    {"id":"4",
      "Vendor Code":"1045",
      "Title":"sdgjoig sfldjsfd",
      "Price":4,
      "Prev Price":350,
       "img":"https://picsum.photos/id/3/200"
    },
    {"id":"5",
      "Vendor Code":"1055",
      "Title":"sdgjoig sfldjsfd",
      "Price":5,
      "Prev Price":350,
       "img":"https://picsum.photos/id/4/200"
    },
    {"id":"6",
      "Vendor Code":"1065",
      "Title":"sdgjoig sfldjsfd",
      "Price":6,
      "Prev Price":350,
       "img":"https://picsum.photos/id/5/200"
    },
    {"id":"7",
      "Vendor Code":"1075",
      "Title":"sdgjoig sfldjsfd",
      "Price":7,
      "Prev Price":350,
       "img":"https://picsum.photos/id/6/200"
    },
    {"id":"8",
      "Vendor Code":"1085",
      "Title":"sdgjoig sfldjsfd",
      "Price":8,
      "Prev Price":350,
       "img":"https://picsum.photos/id/7/200"
    },
    {"id":"9",
      "Vendor Code":"1095",
      "Title":"sdgjoig sfldjsfd",
      "Price":9,
      "Prev Price":350,
       "img":"https://picsum.photos/id/8/200"
    },
    {"id":"10",
      "Vendor Code":"1105",
      "Title":"sdgjoig sfldjsfd",
      "Price":10,
      "Prev Price":350,
       "img":"https://picsum.photos/id/9/200"
    },
    {"id":"11",
      "Vendor Code":"1115",
      "Title":"sdgjoig sfldjsfd",
      "Price":11,
      "Prev Price":350,
       "img":"https://picsum.photos/id/10/200"
    },
    {"id":"12",
      "Vendor Code":"1015",
      "Title":"Lego",
      "Price":12,
      "Prev Price":350,
      "img":"https://picsum.photos/200"
    },
    {"id":"13",
      "Vendor Code":"1025",
      "Title":"sdgjoig sfldjsfd",
      "Price":13,
      "Prev Price":350,
      "img":"https://picsum.photos/id/1/200"
    },
    {"id":"14",
      "Vendor Code":"1035",
      "Title":"sdgjoig sfldjsfd",
      "Price":14,
      "Prev Price":350,
       "img":"https://picsum.photos/id/2/200"
    },
    {"id":"15",
      "Vendor Code":"1045",
      "Title":"sdgjoig sfldjsfd",
      "Price":15,
      "Prev Price":350,
       "img":"https://picsum.photos/id/3/200"
    },
    {"id":"16",
      "Vendor Code":"1055",
      "Title":"sdgjoig sfldjsfd",
      "Price":16,
      "Prev Price":350,
       "img":"https://picsum.photos/id/4/200"
    },
    {"id":"17",
      "Vendor Code":"1065",
      "Title":"sdgjoig sfldjsfd",
      "Price":17,
      "Prev Price":350,
       "img":"https://picsum.photos/id/5/200"
    },
    {"id":"18",
      "Vendor Code":"1075",
      "Title":"sdgjoig sfldjsfd",
      "Price":18,
      "Prev Price":350,
       "img":"https://picsum.photos/id/6/200"
    },
    {"id":"19",
      "Vendor Code":"1085",
      "Title":"sdgjoig sfldjsfd",
      "Price":19,
      "Prev Price":350,
       "img":"https://picsum.photos/id/7/200"
    },
    {"id":"20",
      "Vendor Code":"1095",
      "Title":"sdgjoig sfldjsfd",
      "Price":20,
      "Prev Price":350,
       "img":"https://picsum.photos/id/8/200"
    },
    {"id":"21",
      "Vendor Code":"1105",
      "Title":"sdgjoig sfldjsfd",
      "Price":21,
      "Prev Price":350,
       "img":"https://picsum.photos/id/9/200"
    },
    {"id":"22",
      "Vendor Code":"1115",
      "Title":"sdgjoig sfldjsfd",
      "Price":322,
      "Prev Price":350,
       "img":"https://picsum.photos/id/10/200"
    },  {"id":"1",
      "Vendor Code":"1015",
      "Title":"Lego",
      "Price":1,
      "Prev Price":350,
      "img":"https://picsum.photos/200"
    },
    {"id":"2",
      "Vendor Code":"1025",
      "Title":"sdgjoig sfldjsfd",
      "Price":2,
      "Prev Price":350,
      "img":"https://picsum.photos/id/1/200"
    },
    {"id":"3",
      "Vendor Code":"1035",
      "Title":"sdgjoig sfldjsfd",
      "Price":3,
      "Prev Price":350,
       "img":"https://picsum.photos/id/2/200"
    },
    {"id":"4",
      "Vendor Code":"1045",
      "Title":"sdgjoig sfldjsfd",
      "Price":4,
      "Prev Price":350,
       "img":"https://picsum.photos/id/3/200"
    },
    {"id":"5",
      "Vendor Code":"1055",
      "Title":"sdgjoig sfldjsfd",
      "Price":5,
      "Prev Price":350,
       "img":"https://picsum.photos/id/4/200"
    },
    {"id":"6",
      "Vendor Code":"1065",
      "Title":"sdgjoig sfldjsfd",
      "Price":6,
      "Prev Price":350,
       "img":"https://picsum.photos/id/5/200"
    },
    {"id":"7",
      "Vendor Code":"1075",
      "Title":"sdgjoig sfldjsfd",
      "Price":7,
      "Prev Price":350,
       "img":"https://picsum.photos/id/6/200"
    },
    {"id":"8",
      "Vendor Code":"1085",
      "Title":"sdgjoig sfldjsfd",
      "Price":8,
      "Prev Price":350,
       "img":"https://picsum.photos/id/7/200"
    },
    {"id":"9",
      "Vendor Code":"1095",
      "Title":"sdgjoig sfldjsfd",
      "Price":9,
      "Prev Price":350,
       "img":"https://picsum.photos/id/8/200"
    },
    {"id":"10",
      "Vendor Code":"1105",
      "Title":"sdgjoig sfldjsfd",
      "Price":10,
      "Prev Price":350,
       "img":"https://picsum.photos/id/9/200"
    },
    {"id":"11",
      "Vendor Code":"1115",
      "Title":"sdgjoig sfldjsfd",
      "Price":11,
      "Prev Price":350,
       "img":"https://picsum.photos/id/10/200"
    },
    {"id":"12",
      "Vendor Code":"1015",
      "Title":"Lego",
      "Price":12,
      "Prev Price":350,
      "img":"https://picsum.photos/200"
    },
    {"id":"13",
      "Vendor Code":"1025",
      "Title":"sdgjoig sfldjsfd",
      "Price":13,
      "Prev Price":350,
      "img":"https://picsum.photos/id/1/200"
    },
    {"id":"14",
      "Vendor Code":"1035",
      "Title":"sdgjoig sfldjsfd",
      "Price":14,
      "Prev Price":350,
       "img":"https://picsum.photos/id/2/200"
    },
    {"id":"15",
      "Vendor Code":"1045",
      "Title":"sdgjoig sfldjsfd",
      "Price":15,
      "Prev Price":350,
       "img":"https://picsum.photos/id/3/200"
    },
    {"id":"16",
      "Vendor Code":"1055",
      "Title":"sdgjoig sfldjsfd",
      "Price":16,
      "Prev Price":350,
       "img":"https://picsum.photos/id/4/200"
    },
    {"id":"17",
      "Vendor Code":"1065",
      "Title":"sdgjoig sfldjsfd",
      "Price":17,
      "Prev Price":350,
       "img":"https://picsum.photos/id/5/200"
    },
    {"id":"18",
      "Vendor Code":"1075",
      "Title":"sdgjoig sfldjsfd",
      "Price":18,
      "Prev Price":350,
       "img":"https://picsum.photos/id/6/200"
    },
    {"id":"19",
      "Vendor Code":"1085",
      "Title":"sdgjoig sfldjsfd",
      "Price":19,
      "Prev Price":350,
       "img":"https://picsum.photos/id/7/200"
    },
    {"id":"20",
      "Vendor Code":"1095",
      "Title":"sdgjoig sfldjsfd",
      "Price":20,
      "Prev Price":350,
       "img":"https://picsum.photos/id/8/200"
    },
    {"id":"21",
      "Vendor Code":"1105",
      "Title":"sdgjoig sfldjsfd",
      "Price":21,
      "Prev Price":350,
       "img":"https://picsum.photos/id/9/200"
    },
    {"id":"22",
      "Vendor Code":"1115",
      "Title":"sdgjoig sfldjsfd",
      "Price":322,
      "Prev Price":350,
       "img":"https://picsum.photos/id/10/200"
    }
]
export default data